autoMsgDelayInMin: 15
autoMsgToConsole: false
autoMsgPrefix: '&d[Viktig Beskjed] '
RestartTimeInHours: 0
FileDir: plugins/LarvikGaming/files
PluginsList: true
FileCopyDelayInMin: 10
LogFileCopyTime: false
FilesToCopy:
- server.log
FilesToSave:
- server.txt
LogGetGroupTime: false
RefreshGroupInMin: 0
WorldToGetGroupFrom: world
Groups:
- owner
- admin
- mod
- vip
TimeFormat: yyyy-MM-dd HH:mm:ss
CmdToLog1:
- /town add *
CmdToLog2:
- /money pay *
PrivMsgToLog:
- /message
- /msg
- /reply
- /r
Chat: true
Full-Logger: true
Fine-Logger: false
Info-Logger: false
Warning-Logger: true
Severe-Logger: true