TeleportCharge: 30
autoMsgDelayInMin: 20
autoMsgToConsole: false
autoMsgPrefix: '&d[Viktig Beskjed] '
autoWorldSaveInMin: 15
RestartTimeInHours: 6
FileDir: plugins/LarvikGaming/files
TimeBetweenOnlinePlayersLog: 15
LogGetGroupTime: false
RefreshGroupInMin: 0
WorldToGetGroupFrom: world
Groups:
- owner
- admin
- mod
- vip
TimeFormat: yyyy-MM-dd HH:mm:ss
CmdToLog:
- /town add *
PrivMsgToLog:
- /message
- /msg
- /reply
- /r
Chat: true
Full-Logger: true
Fine-Logger: false
Info-Logger: false
Warning-Logger: true
Severe-Logger: true