name: LarvikGaming
version: 1.0
author: Kiwz

main: net.kiwz.larvikgaming.LarvikGaming

loadbefore: [NoCheatPlus, WorldEdit, Multiverse-Core, Vault, AdminCmd, Craftconomy3, bPermissions, Orebfuscator, WorldBorder]

commands:
  lgtest:
  lginfo:
    description: Prints out information included commands.
    aliases: [lgi, lg]
    permission: larvikgaming.info
    permission-message: You do not have <larvikgaming.info> permission!
    usage: Syntax error! Simply type /<lg>.
  lgrestart:
    description: Restarts the whole server.
    aliases: [lgrs]
    permission: larvikgaming.restart
    permission-message: You do not have <larvikgaming.restart> permission!
    usage: Syntax error! Simply type /<lgrestart>.
  lgreload:
    description: Reloads this plugin.
    aliases: [lgrl]
    permission: larvikgaming.reload
    permission-message: You do not have <larvikgaming.reload> permission!
    usage: Syntax error! Simply type /<lgreload>.
  lggroups:
    description: Gets groups of players.
    aliases: [lgg, groups]
    permission: larvikgaming.groups
    permission-message: You do not have <larvikgaming.groups> permission!
    usage: Syntax error! Simply type /<lggroups> to get groups.
  restart:
    description: Gives information about time untill next restart.
    aliases: [rs]
    permission: 
    permission-message: 
    usage: Syntax error! Simply type /<restart> to get time untill next restart.

permissions:
  larvikgaming.*:
    description: Gives access to all LarvikGaming commands.
    children:
      larvikgaming.test: true
      larvikgaming.info: true
      larvikgaming.restart: true
      larvikgaming.reload: true
      larvikgaming.groups: true
      larvikgaming.freetp: true
  larvikgaming.info:
    description: Prints out information included commands.
    default: op
  larvikgaming.restart:
    description: Restarts the whole server.
    default: op
  larvikgaming.reload:
    description: Reloads this plugin.
    default: op
  larvikgaming.groups:
    description: Create a user.txt file that contains groups of players.
    default: op
  larvikgaming.freetp:
    description: You will not be charged for using /tp commando.
    default: op