name: LarvikGaming
version: 1.0
author: Kiwz

main: net.kiwz.larvikgaming.LarvikGaming

loadbefore: [NoCheatPlus, WorldEdit, Multiverse-Core, Vault, AdminCmd, Craftconomy3, bPermissions, Orebfuscator, WorldBorder]

commands:
  lgtest:
    permission: larvikgaming.test
  lginfo:
    description: Prints out information included commands.
    aliases: [lgi, lg]
    permission: larvikgaming.info
    permission-message: You do not have <larvikgaming.info> permission!
    usage: Syntax error! Simply type /<lg>.
  lgstop:
    description: Stops the whole server with a kick message.
    aliases: [lgs]
    permission: larvikgaming.stop
    permission-message: You do not have <larvikgaming.stop> permission!
    usage: Syntax error! Simply type /<lgstop>.
  lggroups:
    description: Gets groups of players.
    aliases: [lgg, groups]
    permission: larvikgaming.groups
    permission-message: You do not have <larvikgaming.groups> permission!
    usage: Syntax error! Simply type /<lggroups> to get groups.
  lgrestart:
    description: Gives information about time untill next restart.
    aliases: [rs, restart]
    permission: larvikgaming.restart
    permission-message: You do not have <larvikgaming.restart> permission!
    usage: Syntax error! Simply type /<lgrestart> to get time untill next restart.

permissions:
  larvikgaming.*:
    description: Gives access to all LarvikGaming commands.
    children:
      larvikgaming.test: true
      larvikgaming.info: true
      larvikgaming.stop: true
      larvikgaming.groups: true
      larvikgaming.restart: true
      larvikgaming.freetp: true
      larvikgaming.tab.*: true
  larvikgaming.test:
    default: op
  larvikgaming.info:
    description: Prints out information included commands.
    default: op
  larvikgaming.stop:
    description: Stops the whole server with a kick message.
    default: op
  larvikgaming.groups:
    description: Create a user.txt file that contains groups of players.
    default: op
  larvikgaming.restart:
    description: Gives information about time untill next restart.
    default: true
  larvikgaming.freetp:
    description: You will not be charged for using /tp commando.
    default: op
  larvikgaming.tab.*:
    description: You will get a color in the tablist (* = red).
    default: op